export interface Infraction {
  code: string;
  article: string;
  description: string;
  categorie: string;
  classe: number;
  amende: string;
  points: number;
}

export const infractions: Infraction[] = [
  {
    code: "R412-6",
    article: "Art. R412-6 CR",
    description: "Non-respect des limitations de vitesse (excès < 20 km/h)",
    categorie: "Vitesse",
    classe: 4,
    amende: "135 €",
    points: 1,
  },
  {
    code: "R413-14",
    article: "Art. R413-14 CR",
    description: "Excès de vitesse entre 20 et 30 km/h",
    categorie: "Vitesse",
    classe: 4,
    amende: "135 €",
    points: 2,
  },
  {
    code: "R413-14-2",
    article: "Art. R413-14 CR",
    description: "Excès de vitesse entre 30 et 40 km/h",
    categorie: "Vitesse",
    classe: 4,
    amende: "135 €",
    points: 3,
  },
  {
    code: "R413-14-3",
    article: "Art. R413-14 CR",
    description: "Excès de vitesse entre 40 et 50 km/h",
    categorie: "Vitesse",
    classe: 4,
    amende: "135 €",
    points: 4,
  },
  {
    code: "R413-14-4",
    article: "Art. R413-14 CR",
    description: "Excès de vitesse supérieur à 50 km/h",
    categorie: "Vitesse",
    classe: 5,
    amende: "1 500 €",
    points: 6,
  },
  {
    code: "R234-1",
    article: "Art. R234-1 CR",
    description: "Conduite sous l'empire d'un état alcoolique (0,50 à 0,80 g/L)",
    categorie: "Alcool",
    classe: 4,
    amende: "135 €",
    points: 6,
  },
  {
    code: "R234-1-2",
    article: "Art. R234-1 CR",
    description: "Conduite avec alcoolémie ≥ 0,80 g/L",
    categorie: "Alcool",
    classe: 5,
    amende: "4 500 €",
    points: 6,
  },
  {
    code: "R234-1-3",
    article: "Art. R234-1 CR",
    description: "Refus de se soumettre aux épreuves d'alcoolémie",
    categorie: "Alcool",
    classe: 5,
    amende: "4 500 €",
    points: 6,
  },
  {
    code: "R412-6-1",
    article: "Art. R412-6 CR",
    description: "Non-port de la ceinture de sécurité",
    categorie: "Sécurité",
    classe: 4,
    amende: "135 €",
    points: 3,
  },
  {
    code: "R412-1",
    article: "Art. R412-1 CR",
    description: "Utilisation du téléphone tenu en main",
    categorie: "Sécurité",
    classe: 4,
    amende: "135 €",
    points: 3,
  },
  {
    code: "R431-1",
    article: "Art. R431-1 CR",
    description: "Non-respect d'un feu rouge ou d'un stop",
    categorie: "Signalisation",
    classe: 4,
    amende: "135 €",
    points: 4,
  },
  {
    code: "R417-10",
    article: "Art. R417-10 CR",
    description: "Stationnement gênant",
    categorie: "Stationnement",
    classe: 3,
    amende: "35 €",
    points: 0,
  },
  {
    code: "R417-10-2",
    article: "Art. R417-10 CR",
    description: "Stationnement très gênant",
    categorie: "Stationnement",
    classe: 4,
    amende: "135 €",
    points: 0,
  },
  {
    code: "R412-6-2",
    article: "Art. R412-6 CR",
    description: "Défaut de permis de conduire",
    categorie: "Documents",
    classe: 4,
    amende: "135 €",
    points: 0,
  },
  {
    code: "L224-16",
    article: "Art. L224-16 CR",
    description: "Conduite sans assurance",
    categorie: "Documents",
    classe: 5,
    amende: "3 750 €",
    points: 0,
  },
  {
    code: "R412-6-3",
    article: "Art. R412-6 CR",
    description: "Défaut de contrôle technique",
    categorie: "Documents",
    classe: 4,
    amende: "135 €",
    points: 0,
  },
  {
    code: "R431-13",
    article: "Art. R431-13 CR",
    description: "Non-respect de la priorité à droite",
    categorie: "Priorité",
    classe: 4,
    amende: "135 €",
    points: 4,
  },
  {
    code: "R412-2",
    article: "Art. R412-2 CR",
    description: "Circulation à contre-sens",
    categorie: "Circulation",
    classe: 4,
    amende: "135 €",
    points: 4,
  },
  {
    code: "R412-6-4",
    article: "Art. R412-6 CR",
    description: "Non-port du casque (deux-roues)",
    categorie: "Sécurité",
    classe: 4,
    amende: "135 €",
    points: 3,
  },
  {
    code: "R227-1",
    article: "Art. R227-1 CR",
    description: "Conduite sous l'empire de stupéfiants",
    categorie: "Stupéfiants",
    classe: 5,
    amende: "4 500 €",
    points: 6,
  },
];

export const categories = [...new Set(infractions.map((i) => i.categorie))];
